// src/components/Awards.tsx
import { useStore } from "@state/useStore"

import { Section } from "@components/Section"

export function Awards({
  index,
  eyebrow,
}: {
  index?: number
  eyebrow?: string
}) {
  const { awards } = useStore()

  return (
    <Section title="Awards" index={index} eyebrow={eyebrow}>
      <ul>
        {awards.map((a) => (
          <li key={a.name + a.year}>
            <strong>{a.name}</strong> — {a.organization} ({a.year})
          </li>
        ))}
      </ul>
    </Section>
  )
}

// src/angular/components/awards.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
} from "@angular/core"

import { SectionComponent } from "@ngapp/components/section.component"
import { ResumeDataService } from "@ngapp/services/resume-data.service"

@Component({
  selector: "app-awards",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SectionComponent],
  template: `
    <app-section title="Awards" [index]="index()" [eyebrow]="eyebrow()">
      <ul>
        @for (award of awards; track $index) {
          <li>
            <span>
              <strong>{{ award.name }}</strong> — {{ award.organization }} ({{
                award.year
              }})
            </span>
          </li>
        }
      </ul>
    </app-section>
  `,
})
export class AwardsComponent {
  readonly index = input<number>()
  readonly eyebrow = input<string>()

  readonly awards = inject(ResumeDataService).data.awards
}
