// src/components/Footer.tsx
import styles from "@components/Footer.module.css"

import { useStore } from "@state/useStore"

import { stripProtocol } from "@utils/contact"

export function Footer() {
  const name = useStore((s) => s.name)
  const contact = useStore((s) => s.contact)
  const github = contact.find((c) => c.value.includes("github.com"))?.value
  const githubLabel = github && stripProtocol(github)
  return (
    <footer className={styles.footer}>
      <small className={styles.stack}>
        Built with React + Typescript + Vite
      </small>
      <small className={styles.year}>
        {" "}
        © {new Date().getFullYear()}. Codebender Inc.
      </small>
      <small className={styles.credit}>
        {name}
        {github && (
          <>
            {" · "}
            <a href={github} target="_blank" rel="noopener noreferrer">
              {githubLabel}
            </a>
          </>
        )}
      </small>
    </footer>
  )
}

// src/angular/components/footer.component.ts
import { ChangeDetectionStrategy, Component, inject } from "@angular/core"

import { ResumeDataService } from "@ngapp/services/resume-data.service"

import { stripProtocol } from "@utils/contact"

@Component({
  selector: "app-footer",
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrl: "./footer.component.css",
  template: `
    <footer class="footer">
      <small class="stack">Built with Angular + Typescript + Vite</small>
      <small class="year">© {{ year }}. Codebender Inc.</small>
      <small class="credit">
        {{ name }}
        @if (github !== null) {
          {{ " · " }}
          <a [href]="github" target="_blank" rel="noopener noreferrer">
            {{ githubLabel }}
          </a>
        }
      </small>
    </footer>
  `,
})
export class FooterComponent {
  private readonly resume = inject(ResumeDataService)

  readonly name = this.resume.data.name
  readonly github =
    this.resume.data.contact.find((entry) => entry.value.includes("github.com"))
      ?.value ?? null
  readonly githubLabel = this.github !== null ? stripProtocol(this.github) : ""
  readonly year = new Date().getFullYear()
}
