// src/components/Languages.tsx
import { useStore } from "@state/useStore"

import { Section } from "@components/Section"

export function Languages({
  index,
  eyebrow,
}: {
  index?: number
  eyebrow?: string
}) {
  const { languages } = useStore()

  return (
    <Section title="Languages" index={index} eyebrow={eyebrow}>
      <ul>
        {languages.map((l) => (
          <li key={l.name}>
            <strong>{l.name}:</strong> {l.proficiency}
          </li>
        ))}
      </ul>
    </Section>
  )
}

// src/angular/components/languages.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
} from "@angular/core"

import { SectionComponent } from "@ngapp/components/section.component"
import { ResumeDataService } from "@ngapp/services/resume-data.service"

@Component({
  selector: "app-languages",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SectionComponent],
  template: `
    <app-section title="Languages" [index]="index()" [eyebrow]="eyebrow()">
      <ul>
        @for (language of languages; track $index) {
          <li>
            <span>
              <strong>{{ language.name }}:</strong>
              {{ language.proficiency }}
            </span>
          </li>
        }
      </ul>
    </app-section>
  `,
})
export class LanguagesComponent {
  readonly index = input<number>()
  readonly eyebrow = input<string>()

  readonly languages = inject(ResumeDataService).data.languages
}
