// src/components/Showcase.tsx
import { Section } from "@components/Section"
import styles from "@components/Showcase.module.css"

import { useStore } from "@state/useStore"

export function Showcase({
  index,
  eyebrow,
}: {
  index?: number
  eyebrow?: string
}) {
  const { showcase } = useStore()

  return (
    <Section title="Selected Work" index={index} eyebrow={eyebrow}>
      <ul className={styles.grid}>
        {showcase.map((item) => (
          <li key={item.url}>
            <a
              className={styles.card}
              href={item.url}
              target="_blank"
              rel="noopener noreferrer"
            >
              <span className={styles.frame} aria-hidden>
                <span className={styles.dots}>
                  <span className={styles.dot} />
                  <span className={styles.dot} />
                  <span className={styles.dot} />
                </span>
                <span className={styles.domain}>{item.domain}</span>
              </span>
              <span className={styles.shot}>
                <img
                  src={item.image}
                  alt={`${item.name} website`}
                  loading="lazy"
                />
              </span>
              <span className={styles.body}>
                <span className={styles.titleRow}>
                  <h3 className={styles.name}>{item.name}</h3>
                  <span className={styles.period}>{item.period}</span>
                </span>
                <span className={styles.role}>{item.role}</span>
                <span className={styles.description}>{item.description}</span>
                <span className={styles.tags}>
                  {item.tags.map((tag) => (
                    <span key={tag} className={styles.tag}>
                      {tag}
                    </span>
                  ))}
                </span>
              </span>
            </a>
          </li>
        ))}
      </ul>
    </Section>
  )
}

// src/angular/components/showcase.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
} from "@angular/core"

import { SectionComponent } from "@ngapp/components/section.component"
import { ResumeDataService } from "@ngapp/services/resume-data.service"

@Component({
  selector: "app-showcase",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SectionComponent],
  styleUrl: "./showcase.component.css",
  template: `
    <app-section title="Selected Work" [index]="index()" [eyebrow]="eyebrow()">
      <ul class="grid">
        @for (item of showcase; track item.url) {
          <li>
            <a
              class="card"
              [href]="item.url"
              target="_blank"
              rel="noopener noreferrer"
            >
              <span class="frame" aria-hidden="true">
                <span class="dots">
                  <span class="dot"></span>
                  <span class="dot"></span>
                  <span class="dot"></span>
                </span>
                <span class="domain">{{ item.domain }}</span>
              </span>
              <span class="shot">
                <img
                  [src]="item.image"
                  [alt]="item.name + ' website'"
                  loading="lazy"
                />
              </span>
              <span class="body">
                <span class="titleRow">
                  <h3 class="name">{{ item.name }}</h3>
                  <span class="period">{{ item.period }}</span>
                </span>
                <span class="role">{{ item.role }}</span>
                <span class="description">{{ item.description }}</span>
                <span class="tags">
                  @for (tag of item.tags; track tag) {
                    <span class="tag">{{ tag }}</span>
                  }
                </span>
              </span>
            </a>
          </li>
        }
      </ul>
    </app-section>
  `,
})
export class ShowcaseComponent {
  readonly index = input<number>()
  readonly eyebrow = input<string>()

  readonly showcase = inject(ResumeDataService).data.showcase
}
