// src/angular/components/work-experience.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
} from "@angular/core"

import { SectionComponent } from "@ngapp/components/section.component"
import { ResumeDataService } from "@ngapp/services/resume-data.service"

import { employmentParts } from "@utils/employment"
import { experienceDuration } from "@utils/experienceDuration"

@Component({
  selector: "app-work-experience",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SectionComponent],
  styleUrl: "./work-experience.component.css",
  template: `
    <app-section
      title="Work Experience"
      [index]="index()"
      [eyebrow]="eyebrow()"
    >
      <ul class="timeline">
        @for (experience of experiences; track $index) {
          <li>
            <div class="item">
              <div class="header">
                <div>
                  <h3>{{ experience.role }}</h3>
                  <p class="muted">{{ experience.company }}</p>
                </div>
                <span class="period">
                  {{ experience.period }}
                  @if (experience.duration !== null) {
                    <span class="duration">{{ experience.duration }}</span>
                  }
                  @if (experience.employment.length) {
                    <span class="employment">
                      @for (part of experience.employment; track part.key) {
                        @if (!$first) {
                          <span>{{ " · " }}</span>
                        }
                        <span [style.color]="part.color">{{ part.label }}</span>
                      }
                    </span>
                  }
                </span>
              </div>
              <ul class="bullets">
                @for (achievement of experience.achievements; track $index) {
                  <li>{{ achievement }}</li>
                }
              </ul>
            </div>
          </li>
        }
      </ul>
    </app-section>
  `,
})
export class WorkExperienceComponent {
  readonly index = input<number>()
  readonly eyebrow = input<string>()

  readonly experiences = inject(ResumeDataService).data.work_experience.map(
    (experience) => ({
      ...experience,
      duration: experienceDuration(experience.period),
      employment: employmentParts(experience).map((part) => ({
        ...part,
        color: `var(--employment-${part.key})`,
      })),
    })
  )
}

// src/components/WorkExperience.tsx
import { Section } from "@components/Section"
import styles from "@components/WorkExperience.module.css"

import { useEditing } from "@edit/EditContext"
import { EditableText } from "@edit/EditableText"
import { SortableItem, SortableList } from "@edit/SortableList"
import sortStyles from "@edit/SortableList.module.css"

import { useStore } from "@state/useStore"

import { experienceDuration } from "@utils/experienceDuration"

export function WorkExperience({
  index,
  eyebrow,
}: {
  index?: number
  eyebrow?: string
}) {
  const { work_experience } = useStore()
  const { editing, markDirty } = useEditing()
  const store = useStore.getState()

  const act = (fn: () => void) => () => {
    fn()
    markDirty()
  }

  return (
    <Section title="Work Experience" index={index} eyebrow={eyebrow}>
      <SortableList
        count={work_experience.length}
        onReorder={(from, to) => store.reorder(["work_experience"], from, to)}
      >
        <ul className={styles.timeline}>
          {work_experience.map((w, wi) => {
            const duration = experienceDuration(w.period)
            return (
              <SortableItem key={wi} index={wi} label={`experience ${wi + 1}`}>
                {(experienceHandle) => (
                  <div className={styles.item}>
                    <div className={styles.header}>
                      <div>
                        <h3>
                          <EditableText
                            value={w.role}
                            path={["work_experience", wi, "role"]}
                            ariaLabel={`Role ${wi + 1}`}
                          />
                        </h3>
                        <p className={styles.muted}>
                          <EditableText
                            value={w.company}
                            path={["work_experience", wi, "company"]}
                            ariaLabel={`Company ${wi + 1}`}
                          />
                        </p>
                      </div>
                      <span className={styles.period}>
                        <EditableText
                          value={w.period}
                          path={["work_experience", wi, "period"]}
                          ariaLabel={`Period ${wi + 1}`}
                        />
                        {duration && (
                          <span className={styles.duration}>{duration}</span>
                        )}
                      </span>
                    </div>

                    {editing && (
                      <div className={styles.rowControls}>
                        {experienceHandle}
                        <button
                          type="button"
                          aria-label={`Remove experience ${wi + 1}`}
                          onClick={act(() => store.removeExperience(wi))}
                        >
                          ✕
                        </button>
                      </div>
                    )}

                    <SortableList
                      count={w.achievements.length}
                      onReorder={(from, to) =>
                        store.reorder(
                          ["work_experience", wi, "achievements"],
                          from,
                          to
                        )
                      }
                    >
                      <ul
                        className={
                          editing
                            ? `${styles.bullets} ${styles.bulletCards} ${sortStyles.cardList}`
                            : styles.bullets
                        }
                      >
                        {w.achievements.map((a, ai) => (
                          <SortableItem
                            key={ai}
                            index={ai}
                            label={`achievement ${wi + 1}.${ai + 1}`}
                            className={editing ? sortStyles.rowCard : undefined}
                          >
                            {(achievementHandle) => (
                              <>
                                {achievementHandle}
                                <EditableText
                                  value={a}
                                  path={[
                                    "work_experience",
                                    wi,
                                    "achievements",
                                    ai,
                                  ]}
                                  multiline
                                  ariaLabel={`Achievement ${wi + 1}.${ai + 1}`}
                                />
                                {editing && (
                                  <button
                                    type="button"
                                    className={sortStyles.removeButton}
                                    aria-label={`Remove achievement ${wi + 1}.${ai + 1}`}
                                    onClick={act(() =>
                                      store.removeAchievement(wi, ai)
                                    )}
                                  >
                                    ✕
                                  </button>
                                )}
                              </>
                            )}
                          </SortableItem>
                        ))}
                      </ul>
                    </SortableList>

                    {editing && (
                      <button
                        type="button"
                        className={styles.addButton}
                        aria-label={`Add achievement to experience ${wi + 1}`}
                        onClick={act(() => store.addAchievement(wi))}
                      >
                        + Add achievement
                      </button>
                    )}
                  </div>
                )}
              </SortableItem>
            )
          })}
        </ul>
      </SortableList>

      {editing && (
        <button
          type="button"
          className={styles.addButton}
          onClick={act(() => store.addExperience())}
        >
          + Add experience
        </button>
      )}
    </Section>
  )
}
